-- AlterTable
ALTER TABLE "meal_items" ADD COLUMN     "fiber" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "fiber100g" DOUBLE PRECISION,
ADD COLUMN     "sugar" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "sugar100g" DOUBLE PRECISION;
